name: Build, Test, Deploy

on:
  push:
    branches:
      - main

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checking out code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image and push it to Docker Hub
      - name: Build Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME_2: ${{ vars.DOCKER_IMAGE_NAME_2 }}
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME_2 .

      - name: Push Docker image
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_IMAGE_NAME_2: ${{ vars.DOCKER_IMAGE_NAME_2 }}
        run: |
          docker tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME_2 $DOCKER_USERNAME/$DOCKER_IMAGE_NAME_2:latest
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME_2:latest